### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by corochann**

### CODE REVIEW

**Comment by delta2323** [comment]
Could you let us know about the bug you want to eliminate?

**Comment by corochann** [comment]
1. retain_smiles -> return_smiles in get_tox21()
otherwise, code does not work at all.

2. train_tox21 works only for 'rsgcn' and 'sparse_rsgcn' method for this branch.
Since, `multiple` attributed is added as hacking way in this branch.

**Comment by corochann** [comment]
Also, I'd like to ignore travis check of this branch.

**Comment by delta2323** [comment]
> I would like to consider integrating this implementation to master branch after chainer is merged.

I agree.

**Comment by corochann** [comment]
> Also, I'd like to ignore travis check of this branch.

I meant just allow this PR to be merged even the Travis fails?

**Pull request merged**
