### PR TITLE
Make the 'plot.py' script dataset-independent.

### PR DESCRIPTION
**Pull request by mihaimorariu**
Since the AUC evaluation is going to be applied to multiple datasets, the plotting of ROC-AUC should not be dataset-specific.

### CODE REVIEW

**Comment by corochann** [comment]
I think either of below is better.

1. keep current design (we need to re-define similar function in each example)
2. make util function inside library to reuse the visualization

**Comment by delta2323** [comment]
@corochann Can I set you as a reviewer or would you like someone to review the PR?

**Comment by corochann** [comment]
Assigned myself. I will discuss with @mihaimorariu about this.

**Comment by delta2323** [comment]
OK, thanks.

**Comment by mihaimorariu** [comment]
@corochann: I would go for your second proposal. Maybe have this function inside `chainer_chemistry.utils.visualization`?

**Comment by mihaimorariu** [comment]
Following the discussion with @corochann, we agreed to keep the plot script inside each example folder, for now. I will, therefore, close this PR.

**Pull request closed without merging**
