### PR TITLE
Force the regressor to report numpy arrays

### PR DESCRIPTION
**Pull request by mihaimorariu**
When training a network on the CPU and using the `Evaluator` class to output the `MAE` or `MSE`, the reported values are scalars. However, when running the same code on the GPU, the reported values become arrays (and the whole output cannot be serialized into a JSON file). There seems to be a bug in Chainer's reporter class, since the conversion to a scalar is not automatically done, in this case. I will report this to the Chainer team, but this PR should be a temporary fix until the issue is settled.

### CODE REVIEW

**Comment by corochann** [comment]
Thank you for PR, Can you check travis?

**Comment by corochann** [comment]
Can you check travis? Maybe `from chainer import cuda` is not imported @mihaimorariu

**Comment by mihaimorariu** [comment]
Thank you! I will fix it, I think I know what the issue is.

**Comment by mihaimorariu** [comment]
All checks have passed, can you please review now?

**Pull request closed without merging**
