### PR TITLE
Add chainer_chemistry.__version__

### PR DESCRIPTION
**Pull request by delta2323**
This PR adds `chainer_chemistry.__version__` which specifies the version of Chainer Chemistry.

### CODE REVIEW

**Comment by corochann** [comment]
What is the reason that we need `_version.py`? Ins't it ok to just add version in `__init__.py` ?

**Comment by delta2323** [comment]
I follow the discussion in chainer/chainer#3628.

**Comment by corochann** [comment]
Could you merge https://github.com/pfnet-research/chainer-chemistry/pull/47
and run the test again?
If test passes, I will merge it.

**Comment by delta2323** [comment]
I kicked travis again.

**Comment by corochann** [comment]
It seems error comes from this PR.
`setup.py ` dont contain `import os`.
Could you check it ?
(and if possible, could you merge #36 at first?)

**Comment by delta2323** [comment]
Sorry, I overlooked the error. I updated the code.

**Comment by corochann** [comment]
LGTM.

**Pull request merged**
