### PR TITLE
Test example faster

### PR DESCRIPTION
**Pull request by corochann**
ROCAUCEvaluator will raise ValueError when only one label is contained in the dataset.
This will stop the whole script, but this is evaluation script and not affect to training.
I added a option to ignore this error so that we can keep running the training. 

It has another benefit that we can make test example faster.

### CODE REVIEW

**Comment by corochann** [comment]
Please merge after #157

**Comment by delta2323** [comment]
Now #157 is merged. Could you merge or rebase the latest master branch?

**Comment by corochann** [comment]
merged

**Comment by corochann** [comment]
Can you merge if it is ok? @delta2323 @mottodora

**Comment by delta2323** [comment]
LGTM

**Pull request merged**
