### PR TITLE
Schnet add h

### PR DESCRIPTION
**Pull request by mist714**
Information of hydrogen atom is necessary to calculate three-dimensional distance accurately.
Therefore, we added a code to calculate the distance by adding hydrogen once, and a code to remove it again if the number of hydrogen increases.

### CODE REVIEW

**Comment by corochann** [comment]
please add `add_Hs` option as kwargs for the method.

Can we check `addHs` is already called or not by checking `mol`'s attrib??
If possible please call `add_Hs` only when `mol` 's addHs is not called yet.

Please remove assert check.

**Comment by corochann** [comment]
Can you update code @mist714 ?

**Comment by mottodora** [comment]
fix by #390

**Comment by corochann** [comment]
done in #390

**Pull request closed without merging**
