### PR TITLE
Defalt params

### PR DESCRIPTION
**Pull request by corochann**

### CODE REVIEW

**Comment by corochann** [comment]
1. set default parameters
 - GGNN
hidden_dim, n_layers
 - MLP
hidden_dim
 - NFP
hidden_dim, n_layers

2. Change argument order
 - GGNN
out_dim first
 - MLP
out_dim first
 - NFP
out_dim first
	- NFPUpdate
	- NFPReadout

SchNet
out_dim first

**Comment by delta2323** [comment]
Please add unit tests for features added.

**Comment by delta2323** [comment]
The following command caused an error in the Tox21 example. Could you check it?

Command
```
python train_tox21.py --method nfp --label NR-AR --conv-layers 1 --gpu -1 --epoch 1 --unit-num 10
```

Log
```
python train_tox21.py --method nfp --label NR-AR --conv-layers 1 --gpu -1 --epoch 1 --unit-num 10

preprocessing dataset...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11764/11764 [00:19<00:00, 611.97it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 296/296 [00:00<00:00, 590.08it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 647/647 [00:00<00:00, 661.97it/s]
Use NFP predictor...
Exception in main training loop: 
Invalid operation is performed in: SigmoidCrossEntropy (Forward)

Expect: in_types[0].shape == in_types[1].shape
Actual: (128, 10) != (128, 1)
Traceback (most recent call last):
  File "/Users/oonokenta/dev/chainer/chainer/training/trainer.py", line 299, in run
    update()
  File "/Users/oonokenta/dev/chainer/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/Users/oonokenta/dev/chainer/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/Users/oonokenta/dev/chainer/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/Users/oonokenta/dev/chainer/chainer/links/model/classifier.py", line 115, in __call__
    self.loss = self.lossfun(self.y, t)
  File "/Users/oonokenta/dev/chainer/chainer/functions/loss/sigmoid_cross_entropy.py", line 129, in sigmoid_cross_entropy
    return SigmoidCrossEntropy(normalize, reduce)(x, t)
  File "/Users/oonokenta/dev/chainer/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/Users/oonokenta/dev/chainer/chainer/function_node.py", line 230, in apply
    self._check_data_type_forward(in_data)
  File "/Users/oonokenta/dev/chainer/chainer/function_node.py", line 298, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/Users/oonokenta/dev/chainer/chainer/function.py", line 130, in check_type_forward
    self._function.check_type_forward(in_types)
  File "/Users/oonokenta/dev/chainer/chainer/functions/loss/sigmoid_cross_entropy.py", line 31, in check_type_forward
    x_type.shape == t_type.shape
  File "/Users/oonokenta/dev/chainer/chainer/utils/type_check.py", line 519, in expect
    expr.expect()
  File "/Users/oonokenta/dev/chainer/chainer/utils/type_check.py", line 477, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train_tox21.py", line 118, in <module>
    main()
  File "train_tox21.py", line 106, in main
    trainer.run()
  File "/Users/oonokenta/dev/chainer/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/Users/oonokenta/.pyenv/versions/anaconda3-4.3.0/envs/anaconda3/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/Users/oonokenta/dev/chainer/chainer/training/trainer.py", line 299, in run
    update()
  File "/Users/oonokenta/dev/chainer/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/Users/oonokenta/dev/chainer/chainer/training/updater.py", line 234, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/Users/oonokenta/dev/chainer/chainer/optimizer.py", line 536, in update
    loss = lossfun(*args, **kwds)
  File "/Users/oonokenta/dev/chainer/chainer/links/model/classifier.py", line 115, in __call__
    self.loss = self.lossfun(self.y, t)
  File "/Users/oonokenta/dev/chainer/chainer/functions/loss/sigmoid_cross_entropy.py", line 129, in sigmoid_cross_entropy
    return SigmoidCrossEntropy(normalize, reduce)(x, t)
  File "/Users/oonokenta/dev/chainer/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "/Users/oonokenta/dev/chainer/chainer/function_node.py", line 230, in apply
    self._check_data_type_forward(in_data)
  File "/Users/oonokenta/dev/chainer/chainer/function_node.py", line 298, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/Users/oonokenta/dev/chainer/chainer/function.py", line 130, in check_type_forward
    self._function.check_type_forward(in_types)
  File "/Users/oonokenta/dev/chainer/chainer/functions/loss/sigmoid_cross_entropy.py", line 31, in check_type_forward
    x_type.shape == t_type.shape
  File "/Users/oonokenta/dev/chainer/chainer/utils/type_check.py", line 519, in expect
    expr.expect()
  File "/Users/oonokenta/dev/chainer/chainer/utils/type_check.py", line 477, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType: 
Invalid operation is performed in: SigmoidCrossEntropy (Forward)

Expect: in_types[0].shape == in_types[1].shape
Actual: (128, 10) != (128, 1)
```

**Comment by corochann** [comment]
Sorry that I fixed tox21 example in next PR #25...
https://github.com/pfnet-research/chainerchem/pull/25/files#diff-8e751980a5a5a7126f90c4d392995e3eR19

**Comment by delta2323** [comment]
[The comment in #25](https://github.com/pfnet-research/chainerchem/pull/25#issue-278658369) says #24 should be merged before #25. But we cannot merge #24 solely unless changes in #25 which fixes the example are incorporated because otherwise this PR breaks the master branch.

So could you consider to choose either way: (1) to fix #24 to run the example code successfully or (2) to review #25 directly?

**Comment by corochann** [comment]
Can we proceed with (2)?

So when both PR#24 & #25 are accepted please merge both.

**Comment by delta2323** [comment]
> Can we proceed with (2)?

OK, are changes in #24 included in #25?

**Comment by corochann** [comment]
yes

**Pull request merged**
